# 7. Osztályok, filekezelés
_2021.10.25_

Tartalom:
- math modul
- Numpy
- Sympy

In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

## 7.1 Math modul
Beépített modul matematikai számításokra.

In [2]:
import math

### 7.1.1 Konstansok

In [3]:
math.e, math.pi, math.inf, math.nan

(2.718281828459045, 3.141592653589793, inf, nan)

### 7.1.2 Trigonometrikus függvények

In [7]:
# Átváltás fokból radiánba és radiánból fokba 
math.radians(90), math.degrees(0)

(1.5707963267948966, 0.0)

In [ ]:
# Alap trigonometrikus függvények
math.sin(1), math.cos(1), math.tan(1)

In [9]:
# Trigonimetrikus függvények és inverzeik
math.sin(math.radians(90)), math.degrees(math.asin(1.0))

(1.0, 90.0)

### 7.1.3 Kombinatorikai függvények

Kombináció (n alatt a k): $$ {n \choose k} = \frac{n!}{k! (n-k)!} $$

In [10]:
math.comb(7, 5), math.factorial(7)/(math.factorial(5)*math.factorial(7-5))

(21, 21.0)

Permutáció (hányféleképpen tudok kiválasztani n-ből k elemet): $$ \frac{n!}{(n - k)!} $$

In [11]:
math.perm(3, 2), math.factorial(3)/math.factorial(3-2)

(6, 6.0)

### 7.1.4 Egyéb

In [13]:
# ceil = plafon (egy számot a legközelebbi nála nagyobb egészre kerekít)
# floor = padló (egy számot a legközelebb nála kisebb egészre kerekít)
math.ceil(7.6), math.floor(-7.6)

(8, -8)

In [14]:
# Euklideszi távolság kiszámítása
math.dist([1, 0], [0, 0])

1.0

In [15]:
# Abszolútérték
math.fabs(8), math.fabs(-8)

(8.0, 8.0)

In [16]:
math.pow(2, 2), math.sqrt(4)

(4.0, 2.0)

In [19]:
# e^x
math.exp(2), math.pow(math.e, 2)

(7.38905609893065, 7.3890560989306495)

In [20]:
# Logaritmusok: természetes, kettes, tizes alapú
math.log(math.e), math.log2(4), math.log10(1000)

(1.0, 2.0, 3.0)

In [22]:
# Osztási maradék
math.fmod(3, 2), 3%2

(1.0, 1)

In [23]:
# Összeg
math.fsum([1, 2, 3, 4])

10.0

In [24]:
# GCD = Greatest Common Divisor = legnagyobb közös osztó
math.gcd(39, 99)

3

In [25]:
# True, ha a paraméterként átadott érték végtelen, egyébként False
math.isinf(5), math.isinf(math.inf)

(False, True)

## 7.2 Numpy
[Numpy](http://www.numpy.org) egy alap Python csomag, matematikai és tudományos számítások elvégzésére.

### 7.2.1 Tömbök
A Numpy tömb egy azonos típusú értékekből álló rács, amelyet nemnegatív egész számok sorozata indexel.

In [26]:
import numpy as np

In [27]:
# Numpy tömb létrehozása
a = np.array([1, 2, 3])

In [28]:
type(a)

numpy.ndarray

In [29]:
# indexekkel lehet az egyes elemekre hivatkozni
a[0], a[1]

(1, 2)

In [30]:
# a tömb méreteinek lekérdezésére
a.shape

(3,)

In [33]:
# 2x3-as tömb létrehozása
b = np.array([[1, 2, 3], [4, 5, 6]]) 

In [34]:
b.shape

(2, 3)

In [36]:
# a 2 dimenziós tömb elemeire 2 index-szel hivatkozunk
b[0, 1]

2

In [37]:
# 2x2-es tömb létrehozása, az egyes rácspontokban lévő elemek: 0
a = np.zeros((2, 2))

In [38]:
a

array([[0., 0.],
       [0., 0.]])

In [39]:
# 1x2-es tömb létrehozása, az egyes rácspontokban lévő elemek: 1
b = np.ones((1, 2))

In [40]:
b

array([[1., 1.]])

In [41]:
# 2x2-es tömb létrehozása, az egyes rácspontokban lévő elemek: 7
c = np.full((2, 2), 7)

In [42]:
c

array([[7, 7],
       [7, 7]])

In [43]:
# 4x4-es identitásmátrix
d = np.eye(4)

In [44]:
d

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [45]:
# 2x2-es mátrix véletlenszerű elemekkel feltöltve
e = np.random.random((2, 2))

In [46]:
e

array([[0.8545137 , 0.46777707],
       [0.17394981, 0.35537752]])

### 7.2.2 Indexelés és szeletelés (slicing)

In [50]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

In [51]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [58]:
a[0, 0], a[0, 1], a[0, 2], a[3, 2]

(1, 2, 3, 12)

In [59]:
b = np.array([0, 2, 0, 1])

In [60]:
a[np.arange(4), b]

array([ 1,  6,  7, 11])

In [47]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [49]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [48]:
a[:2, 1:3]

array([[2, 3],
       [6, 7]])

### 7.2.3 Boolean indexelés
Lehetséges egy Numpy tömböt egy dimenziójában megegyező True/False értékekkel feltöltött tömbbel indexelni. A végeredmény egy 1 dimenziós tömb, amelynek elemei az indexelő tömbben True értékekkel megjelölt elemek.

In [61]:
# Boolean indexlés
a = np.array([[1, 2], [3, 4], [5, 6]])

In [62]:
bool_idx = (a > 2)

In [63]:
bool_idx

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [64]:
a[bool_idx]

array([3, 4, 5, 6])

### 7.2.4 Adattípusok

In [65]:
x = np.array([1, 2])

In [66]:
x.dtype

dtype('int32')

In [67]:
x = np.array([1.0, 2.0])

In [68]:
x.dtype

dtype('float64')

In [69]:
x = np.array([1, 2], dtype=np.int64)

In [70]:
x.dtype

dtype('int64')

### 7.2.5 Matematikai műveletek

In [71]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

In [72]:
# a két tömb egyes elemeinek összege
x + y

array([[ 6.,  8.],
       [10., 12.]])

In [83]:
np.add(x, y)

array([[ 6.,  8.],
       [10., 12.]])

In [74]:
# a két tömb egyes elemeinek különbsége
x - y

array([[-4., -4.],
       [-4., -4.]])

In [75]:
np.subtract(x, y)

array([[-4., -4.],
       [-4., -4.]])

In [84]:
# a két tömb egyes elemeinek szorzata
x * y

array([[ 5., 12.],
       [21., 32.]])

In [77]:
np.multiply(x, y)

array([[ 5., 12.],
       [21., 32.]])

In [78]:
# a két tömb egyes elemeinek hányadosa
x/y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [79]:
np.divide(x, y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [80]:
# a paraméterként átadott tömb egyes elemeinek négyzetgyöke
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [85]:
v = np.array([9, 10])
w = np.array([11, 12])

In [89]:
# Skalárszorzat
v.dot(w), np.dot(v, w), 9*11 + 10*12

(219, 219, 219)

In [90]:
x = np.array([[1, 2], [3, 4]])

In [91]:
x

array([[1, 2],
       [3, 4]])

In [92]:
# Transzponált
x.T

array([[1, 3],
       [2, 4]])

In [93]:
# Tömbben található számok összege
np.sum(x)

10

In [94]:
np.sum(x, axis=0)

array([4, 6])

In [95]:
np.sum(x, axis=1)

array([3, 7])

### 7.2.6 Broadcasting

In [96]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])

In [97]:
# létrehoz egy 0-ás értékekkel feltöltött tömböt, amely méreteit tekintve megegyezik a paraméterként átadott tömbbel
y = np.empty_like(x)

In [98]:
y

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [101]:
# Második index helyett minden indexet átadunk, amelyet egy :-tal jelölünk
for i in range(4):
    y[i, :] = x[i, :] + v

In [100]:
y

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [102]:
# elkészít egy tömböt, amelyet az első paraméterként átadott értékekkel tölt fel, mérete a második paraméterben átadott értékek
vv = np.tile(v, (4, 1))

In [104]:
v, vv

(array([1, 0, 1]),
 array([[1, 0, 1],
        [1, 0, 1],
        [1, 0, 1],
        [1, 0, 1]]))

In [105]:
x+vv

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [106]:
x+v

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [110]:
# tömböt átméretezésére szolgál
np.reshape(x+v, (2, 6))

array([[ 2,  4,  6,  5,  7,  9],
       [ 8, 10, 12, 11, 13, 15]])

> **1. feladat**: Írj egy függvényt, amely első paraméterként átadott 2D tömbből kinyeri azokat az értékeket, amelyek a második 2D tömbben is megtalálhatóak!

In [119]:
def common_values(a, b):
    a = a.flatten() # használható a reshape függvény is
    b = b.flatten()
    o = []

    for i in a:
        if i not in b:
            o.append(i)
    
    return o

common_values(
    np.array([[0, 10, 20], [30, 40, 50]]),
    np.array([[10, 20, 5], [45, 40, 10]])
)

[0, 30, 50]

> **2. feladat**: Írj egy függvényt, amely visszaadja a paraméterként átadott lista maximumának indexét!

In [121]:
def index_max(l): # np.argmax()
    o = l[0]
    i = 0

    for j in range(len(l)):
        if l[j] > o:
            o = l[j]
            i = j           

    return i
    
index_max([1, 5, 7, 2, 5, 7, 9, 2, 5])

6

> **3. feladat**: Írj egy függvényt, amely kiszámítja a paraméterként átadott n dimenziós Numpy tömbben található számok átlagát!

In [149]:
def atlag(k): # np.average
    k = k.flatten()
    o = 0
    for i in k:
        o += i

    return o/len(k)

atlag(np.array([1, 4, 6, 8, 9]))

5.6

> **4. feladat**: Írj egy függvényt, amely kiszámítja a paraméterként átadott percentilisét a szintén paraméterként átadott tömb értékeiből! (https://hu.wikiqube.net/wiki/Percentile)!

In [160]:
def perc(k, p):
    k = np.sort(k)
    return math.ceil((p/100)*len(k))
    
perc(np.array([2, 1, 5, 3, 4]), 80), perc(np.array([2, 1, 5, 3, 4, 6, 8, 9, 7, 10]), 55)

(4, 6)

## 7.2 Sympy
A [Sympy](https://sympy.org) egy ingyenes Python modul szimbolikus számítások elvégzésére.
Telepítése: _pip install sympy_

In [122]:
# gyökvonás
import sympy
sympy.sqrt(8)

2*sqrt(2)

In [123]:
# kifejezés definiálása
from sympy import symbols
x, y = symbols('x y')
expr = x + 2*y

In [124]:
expr

x + 2*y

In [125]:
expr + 1

x + 2*y + 1

In [126]:
expr-x

2*y

In [127]:
# automatikus kiemelés
x*expr

x*(x + 2*y)

In [128]:
# a paraméterként átadott kifejezést a legegyszerűbb alakra hozza
from sympy import expand, factor
expand(x*expr)

x**2 + 2*x*y

In [129]:
# a pareméterként átadott kifejezésben a közös elemeket kiemeli
factor(x*expr)

x*(x + 2*y)

In [139]:
# a paraméterként átadott kifejezés deriváltja
from sympy import *
diff(sin(x))

cos(x)

In [141]:
# a paraméterként átadott függvény második paraméter szerinti deriváltja
diff(sin(x)*exp(x), x)

exp(x)*sin(x) + exp(x)*cos(x)

In [135]:
# a paraméterként átadott kifejezés integrálja
integrate(exp(x)*sin(x) + exp(x)*cos(x), x)

exp(x)*sin(x)

In [136]:
# a paraméterként átadott függvény integrálja -oo és +oo között
integrate(sin(x**2), (x, -oo, oo))

sqrt(2)*sqrt(pi)/2

Határérték számítása:
$$ lim_{x\to0}f(x) $$, $$ lim_{x\to\infty}f(x) $$

In [145]:
limit(sin(x)/x, x, 0), limit(sin(x)/x, x, oo)

(1, 0)

In [146]:
# megoldja a paraméterként átadott egyenletet
solve(x**2-2, x)

[-sqrt(2), sqrt(2)]

In [147]:
# mátrix egyenértékeinek kiszámítása
Matrix([[1, 2], [2, 2]]).eigenvals()

{3/2 - sqrt(17)/2: 1, 3/2 + sqrt(17)/2: 1}