# 7. Osztályok, filekezelés
_2021.09.26_

Az órán ...

Tartalom:
- Numpy
- Sympy
- Matematikai és statisztikai csomagok

In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

## 7.1 Numpy
[Numpy](http://www.numpy.org) egy alap Python csomag, matematikai és tudományos számítások elvégzésére.

### 7.1.1 Tömbök
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

In [3]:
import numpy as np

In [4]:
a = np.array([1, 2, 3])

In [5]:
type(a)

numpy.ndarray

In [6]:
a[0], a[1]

(1, 2)

In [7]:
a.shape

(3,)

In [8]:
b = np.array([[1,2,3],[4,5,6]]) 

In [9]:
b.shape

(2, 3)

In [10]:
b[0, 1]

2

In [11]:
a = np.zeros((2,2))

In [12]:
a

array([[0., 0.],
       [0., 0.]])

In [13]:
b = np.ones((1,2))

In [14]:
b

array([[1., 1.]])

In [15]:
c = np.full((2,2), 7)

In [16]:
c

array([[7, 7],
       [7, 7]])

In [18]:
d = np.eye(4) # identity matrix

In [19]:
d

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
e = np.random.random((2,2))

In [21]:
e

array([[0.73575461, 0.58943234],
       [0.86728381, 0.38034423]])

Slicing

In [22]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [23]:
a[:2, 1:3]

array([[2, 3],
       [6, 7]])

Indexelés

In [24]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

In [25]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [26]:
b = np.array([0, 2, 0, 1])

In [27]:
a[np.arange(4), b]

array([ 1,  6,  7, 11])

Boolean indexlés

In [29]:
a = np.array([[1,2], [3, 4], [5, 6]])

In [30]:
bool_idx = (a > 2)

In [31]:
bool_idx

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [32]:
a[bool_idx]

array([3, 4, 5, 6])

Datatypes

In [33]:
x = np.array([1, 2])

In [34]:
x.dtype

dtype('int32')

In [35]:
x = np.array([1.0, 2.0])

In [36]:
x.dtype

dtype('float64')

In [37]:
x = np.array([1, 2], dtype=np.int64)

In [38]:
x.dtype

dtype('int64')

Matematikai műveletek

In [39]:
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[5,6], [7,8]], dtype=np.float64)

In [40]:
x+y

array([[ 6.,  8.],
       [10., 12.]])

In [41]:
np.add(x, y)

array([[ 6.,  8.],
       [10., 12.]])

In [42]:
x-y

array([[-4., -4.],
       [-4., -4.]])

In [43]:
np.subtract(x, y)

array([[-4., -4.],
       [-4., -4.]])

In [44]:
x*y

array([[ 5., 12.],
       [21., 32.]])

In [45]:
np.multiply(x, y)

array([[ 5., 12.],
       [21., 32.]])

In [46]:
x/y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [47]:
np.divide(x, y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [48]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [49]:
v = np.array([9, 10])
w = np.array([11, 12])

In [50]:
v.dot(w)

219

In [51]:
np.dot(v, w)

219

In [52]:
x = np.array([[1, 2], [3, 4]])

In [57]:
x

array([[1, 2],
       [3, 4]])

In [58]:
x.T

array([[1, 3],
       [2, 4]])

In [53]:
np.sum(x)

10

In [55]:
np.sum(x, axis=0)

array([4, 6])

In [56]:
np.sum(x, axis=1)

array([3, 7])

Broadcasting

In [59]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])

In [60]:
y = np.empty_like(x)

In [61]:
y

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [62]:
for i in range(4):
    y[i, :] = x[i, :] + v

In [63]:
y

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [65]:
vv = np.tile(v, (4, 1))

In [66]:
x+vv

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [64]:
x+v

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [67]:
v = np.array([1, 2, 3])
w = np.array([4, 5])

In [68]:
np.reshape(v, (3, 1)) * w

array([[ 4,  5],
       [ 8, 10],
       [12, 15]])

In [69]:
x+v

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12],
       [11, 13, 15]])

## 7.2 Sympy
A [Sympy](https://sympy.org) egy ingyenes Python modul szimbolikus számítások elvégzésére.
Telepítése: _pip install sympy_

In [2]:
import math
math.sqrt(9)

3.0

In [3]:
math.sqrt(8)

2.8284271247461903

In [8]:
import sympy
sympy.sqrt(8)

2*sqrt(2)

In [10]:
from sympy import symbols
x, y = symbols('x y')
expr = x + 2*y

In [11]:
expr

x + 2*y

In [12]:
expr + 1

x + 2*y + 1

In [13]:
expr-x

2*y

In [14]:
x*expr

x*(x + 2*y)

In [16]:
from sympy import expand, factor
expand(x*expr)

x**2 + 2*x*y

In [17]:
factor(x*expr)

x*(x + 2*y)

In [19]:
from sympy import *
diff(sin(x))

cos(x)

In [20]:
diff(sin(x)*exp(x), x)

exp(x)*sin(x) + exp(x)*cos(x)

In [21]:
integrate(exp(x)*sin(x) + exp(x)*cos(x), x)

exp(x)*sin(x)

In [22]:
integrate(sin(x**2), (x, -oo, oo))

sqrt(2)*sqrt(pi)/2

In [23]:
limit(sin(x)/x, x, 0)

1

In [24]:
solve(x**2-2, x)

[-sqrt(2), sqrt(2)]

In [25]:
Matrix([[1, 2], [2, 2]]).eigenvals()

{3/2 - sqrt(17)/2: 1, 3/2 + sqrt(17)/2: 1}